---
title: "Field Study dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny 
---

```{r setup, include=FALSE}
pacman::p_load(
  rio,             # data import/export     
  here,            # locate files
  tidyverse,       # data management and visualization
  flexdashboard,   # dashboard versions of R Markdown reports
  shiny,           # interactive figures
  plotly,           # interactive figures
  janitor,
  Knitr,
  KableExtra
)
options(knitr.table.format = "latex")
```

```{r}
 dataset <- eventReactive(input$file1,{
       read_csv(input$file1$datapath)
    })
```

# Ibadan

## Column  {.sidebar data-width=350}

```{r, echo = FALSE}
fileInput("file1", "Upload data. Choose CSV File",
                multiple = TRUE,
                accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv"))


```


<!-- # Data  -->

<!-- ## Row -->

<!-- ### Table 1 - Show the data recently acquired -->

<!-- ```{r} -->

<!-- renderTable({ -->
<!--    dataset <- dataset() -->
<!--    dataset -->
<!--    }) -->
<!-- ``` -->


# plots and tables

## Row

### Table 1 - Show the data recently acquired

```{r}

htmlOutput("tableset")

d <- eventReactive(input$file1,{
dataset()%>%
  count(`NAME OF HEALTH FACILITY`) %>%
  adorn_totals() %>%
  rename("Cases" = n) %>%
  knitr::kable()
})


output$tableset <- renderText({
  d <- d() %>%  kableExtra::kbl() %>%  kableExtra::kable_styling()
  d
})

# renderText({
#    d <- d()
#    d
#    })
```


